# Generated by Django 4.1.6 on 2023-02-14 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pet_walking', '0002_alter_owner_pets_alter_owner_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='walker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walkers', to=settings.AUTH_USER_MODEL),
        ),
    ]
